### ISSUE TITLE
The pure Perl implementation does not agree with Unicode::CheckUTF8

### ISSUE THREAD

**Issue by autarch** [creaktive/Test-Mojibake#10]
With `Unicode::CheckUTF8` not installed, the tests fail on [this file](http://www.urth.org/~autarch/os_GE.pod). After installing, tests pass.

**Comment by creaktive** [comment]
Thanks for finding this, Dave! Could you please check if it now works for other test cases you might have?

**Comment by autarch** [comment]
I'm still getting what I think are false positives - see https://metacpan.org/pod/release/DROLSKY/DateTime-Locale-0.96-TRIAL/lib/DateTime/Locale/my.pod for some text to test against.

**Comment by creaktive** [comment]
Since I've completely forgot how I did implement the PP UTF8 verifier, I'll simply backport ``Unicode::CheckUTF8`` as soon as I have some time, then :)
