### ISSUE TITLE
1.3: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [creaktive/Test-Mojibake#14]
<pre>+ /usr/bin/make -O -j48 V=1 VERBOSE=1 test AUTHOR_TESTING=1 RELEASE_TESTING=1
PERL_DL_NONLAZY=1 &quot;/usr/bin/perl&quot; &quot;-MExtUtils::Command::MM&quot; &quot;-MTest::Harness&quot; &quot;-e&quot; &quot;undef *Test::Harness::Switches; test_harness(0, &apos;blib/lib&apos;, &apos;blib/arch&apos;)&quot; t/*.t
t/00-compile.t ............... ok
# Testing Test::Mojibake v1.3, Perl 5.030001, /usr/bin/perl
# Using Test::Builder v1.302170
t/00-load.t .................. ok
t/01-bad-check.t ............. ok
t/01-self-check.t ............ ok
t/01-test-check.t ............ ok
t/02-bad-source.t ............ ok
t/02-good-source.t ........... ok
t/03-bad-pod.t ............... ok
t/03-good-pod.t .............. ok
t/04-bom.t ................... ok
t/05-encode.t ................ ok
# XS/PP speed ratio is 46.94
t/06-pp-vs-xs.t .............. ok
t/07-broken-utf8.t ........... ok
t/08-all-files-none-found.t .. ok
t/author-critic.t ............ ok
t/author-eol.t ............... ok
t/author-mojibake.t .......... ok
t/author-no-tabs.t ........... ok
t/author-pod-coverage.t ...... ok
t/author-pod-linkcheck.t ..... ok
t/author-pod-syntax.t ........ ok
t/author-portability.t ....... ok
t/author-synopsis.t .......... ok
t/author-test-version.t ...... ok
t/release-cpan-changes.t ..... ok
# Distribution files are missing in MANIFEST:
# debugsources.list
# debugfiles.list
# debuglinks.list
# elfbins.list
# debugsourcefiles.list

#   Failed test &apos;All files are listed in MANIFEST or skipped&apos;
#   at t/release-dist-manifest.t line 16.
# Looks like you failed 1 test of 4.
t/release-dist-manifest.t .... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests 
t/release-distmeta.t ......... ok
t/release-kwalitee.t ......... ok
t/release-meta-json.t ........ ok
t/release-minimum-version.t .. ok
t/release-unused-vars.t ...... ok

Test Summary Report
-------------------
t/release-dist-manifest.t  (Wstat: 256 Tests: 4 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
Files=31, Tests=238, 11 wallclock secs ( 0.18 usr  0.06 sys + 10.03 cusr  0.87 csys = 11.14 CPU)
Result: FAIL
Failed 1/31 test programs. 1/238 subtests failed.
make: *** [Makefile:871: test_dynamic] Error 255
</pre>

**Comment by creaktive** [comment]
Could not reproduce. What is the OS you are building it on?
In any case, you don't need the `AUTHOR_TESTING=1 RELEASE_TESTING=1` flags. Remove these and it will certainly pass.

**Comment by kloczek** [comment]
It is my own Linux with perl 5.30.1.

After remove `AUTHOR_TESTING=1 RELEASE_TESTING=1` test suite passed ok.
(I've took that from Fedora spec files)
